---
title: "Anatomy of Learning, and Downsides of Being a Second-Hand Thinker"
date: 2026-06-25
categories: [thinking, learning]
---

Growing up, I had a constant need of understanding how objects worked, I was constantly curious, was good at math in my peer group and dug my heels in to understand the core elements of any topic.

There though when I hit a wall for long time to learn a more complex topic, I had to make concessions on asking about the why, and accepting what was told as truth, `that's just how it works` and proceeding to use this assumed bedrock to then build the concepts atop.

This particularly happened to keep the pace with the fire hose of syllabus coming towards me, the need to keep with the pace of `learning` the course for the tests and an incomplete and immature system to digest the syllabus with a pin or a bookmark.

Now as I am older and am learning purely for the sake of understanding and out of curiosity for my selfish wants. I want to learn the concepts to their depth. I am not bound by a deadline on within which I have to learn, rather am bound by my limited time — limitations bring out efficiency. I hope to make use of my limited time well by making this an efficient use of time.

## Downside of Second-Hand Thinking

> Be a source, not a relay. — Grant Sanderson

By not understanding a topic completely and relying on another person's explanation, I will not understand the topic at hand. I have not played with it enough to find the nook and cranny of the thought, the way the concept grows and expands, the beauty of it or where its weaknesses lie and where it would collapse. All these aspects are fun to understand, and give a different perspective to the topic at hand as well as a different view of the world.
